### ISSUE TITLE
wath will block if the caller want to stop the watcher...

### ISSUE THREAD

**Issue by qingchundouzsu** [xiaoyulei/kvstore#26]
func (s *Etcd) watch(key string, opt *store.WatchOptions, recursive bool, stopCh <-chan struct{}) (<-chan *store.WatchResponse, error) {
	opts := &etcd.WatcherOptions{Recursive: recursive}
	if opt != nil {
		opts.AfterIndex = opt.Index
	}
	watcher := s.client.Watcher(store.Normalize(key), opts)

	// watchCh is sending back events to the caller
	resp := make(chan *store.WatchResponse)
	go func() {
		defer close(resp)

		for {
			// Check if the watch was stopped by the caller
			select {
			case <-stopCh:
				return
			default:
				r, err := watcher.Next(context.Background())-----will block here if caller want to stop watch , because the Next function is block function and can not receive the stopCh channel. 
				resp <- s.makeWatchResponse(r, err)
				if err != nil {
					return
				}
			}
		}
	}()

	return resp, nil
}

**Comment by xiaoyulei** [comment]
yes, that is a problem.

**Comment by qingchundouzsu** [comment]
ok.
