### ISSUE TITLE
about lock 

### ISSUE THREAD

**Issue by qingchundouzsu** [xiaoyulei/kvstore#28]
1:  can return error if lock failed in the given ttl time ?
2:  not call panic in the lock function ?
3:  if the lock node created by some others before, the lock will fail forever. i think it should succeed

**Comment by xiaoyulei** [comment]
what do you mean about `if the lock node created by some others before, the lock will fail forever. i think it should succeed`? Others already get the lock, I think it should block until release.

**Comment by xiaoyulei** [comment]
About if return error when lock fail, I prefer no return. The latest etcd clientv3 has it own locker, and there is no return value also.
